package jni;
public class TrackingJNI_O {

	/*java send coordinates ((x1, y1), (x2, y2)) to c++ through JNI.
	java send rawFileName and trackingFileName as String type to c++ through JNI.
	rawFileName is String type. It is a full path plus file name. 
	It is the raw video file for c++.
	trackingFileName is String type. It is a full path plus file name. 
	It is the output file generated by c++.
	c++ return true if it c++ has generated tracking video and saved it..
	 * */
	public native boolean trackingMethod(String rawFileName,int x1, int y1, int x2, int y2, String trackingFileName);
	
	public TrackingJNI_O(){}
}
