/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_TrackingJNI */

#ifndef _Included_jni_TrackingJNI
#define _Included_jni_TrackingJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_TrackingJNI
 * Method:    trackingMethod
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_jni_TrackingJNI_trackingMethod
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
